/**
 * Editor
 */
export const EDITOR_CLEAN = 'EDITOR_CLEAN';
export const EDITOR_UPDATE = 'EDITOR_UPDATE';

/**
 * Workspace
 */
export const WORKSPACE_PURGE = 'WORKSPACE_PURGE';
export const WORKSPACE_TAGSWITCH = 'WORKSPACE_TAGSWITCH';
export const WORKSPACE_HISTORY_REMOVE = 'WORKSPACE_HISTORY_REMOVE';
export const WORKSPACE_HISTORY_PURGE = 'WORKSPACE_HISTORY_PURGE';
